Import the 1.17.2 release

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -8,6 +8,31 @@ if [ "$1" = "configure" ]; then
 	chown -R vault: /srv/vault 2>&1 /dev/null || true
 fi
 
-#DEBHELPER#
+# End automatically added section
+# Automatically added by dh_installsystemd/13.16
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+        # The following line should be removed in trixie or trixie+1
+        deb-systemd-helper unmask 'vault.service' >/dev/null || true
+
+        # was-enabled defaults to true, so new installations run enable.
+        if deb-systemd-helper --quiet was-enabled 'vault.service'; then
+                # Enables the unit on first installation, creates new
+                # symlinks on upgrades if the unit file has changed.
+                deb-systemd-helper enable 'vault.service' >/dev/null || true
+        else
+                # Update the statefile to add new symlinks (if any), which need to be
+                # cleaned up on purge. Also remove old symlinks.
+                deb-systemd-helper update-state 'vault.service' >/dev/null || true
+        fi
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/13.16
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+        if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
+                systemctl --system daemon-reload >/dev/null || true
+                deb-systemd-invoke start 'vault.service' >/dev/null || true
+        fi
+fi
+# End automatically added section
 
 exit 0
